name: Deploy Backend
on:
  push:
    branches: [ release/master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ ! -d "/root/kindercare-backend" ]; then
              git clone https://github.com/Kindergarten-Care/kindercare-backend.git /root/kindercare-backend
            fi
            cd /root/kindercare-backend
            git fetch origin
            git checkout release/master
            git pull origin release/master
            docker build -t kindercare-api .
            docker stop kindercare-api || true
            docker rm kindercare-api || true
            docker run -d --name kindercare-api -p 5000:5000 kindercare-api